# Generated by Django 4.2.7 on 2024-04-18 13:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('type', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('type', models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='api.requesttype')),
            ],
        ),
    ]
